<?php

return [
    ['restaurant_id' => 1, 'typology_id' => 1],
    ['restaurant_id' => 2, 'typology_id' => 2],
    ['restaurant_id' => 3, 'typology_id' => 3],
    ['restaurant_id' => 4, 'typology_id' => 4],
    ['restaurant_id' => 5, 'typology_id' => 5],
    ['restaurant_id' => 6, 'typology_id' => 6],
    ['restaurant_id' => 7, 'typology_id' => 7],
    ['restaurant_id' => 8, 'typology_id' => 8],
    ['restaurant_id' => 9, 'typology_id' => 9],
    ['restaurant_id' => 10, 'typology_id' => 10],
    ['restaurant_id' => 11, 'typology_id' => 11],
    ['restaurant_id' => 12, 'typology_id' => 12],
    ['restaurant_id' => 13, 'typology_id' => 13],
    ['restaurant_id' => 14, 'typology_id' => 14],
    ['restaurant_id' => 15, 'typology_id' => 15],
    ['restaurant_id' => 16, 'typology_id' => 16],
    ['restaurant_id' => 17, 'typology_id' => 17],
    ['restaurant_id' => 18, 'typology_id' => 18],
    ['restaurant_id' => 19, 'typology_id' => 19],
    ['restaurant_id' => 20, 'typology_id' => 20],
    ['restaurant_id' => 21, 'typology_id' => 1],
    ['restaurant_id' => 22, 'typology_id' => 2],
    ['restaurant_id' => 23, 'typology_id' => 3],
    ['restaurant_id' => 24, 'typology_id' => 4],
    ['restaurant_id' => 25, 'typology_id' => 5],
    ['restaurant_id' => 26, 'typology_id' => 6],
    ['restaurant_id' => 27, 'typology_id' => 7],
    ['restaurant_id' => 28, 'typology_id' => 8],
    ['restaurant_id' => 29, 'typology_id' => 9],
    ['restaurant_id' => 30, 'typology_id' => 10],
    ['restaurant_id' => 31, 'typology_id' => 11],
    ['restaurant_id' => 32, 'typology_id' => 12],
    ['restaurant_id' => 33, 'typology_id' => 13],
    ['restaurant_id' => 34, 'typology_id' => 14],
    ['restaurant_id' => 35, 'typology_id' => 15],
    ['restaurant_id' => 36, 'typology_id' => 16],
    ['restaurant_id' => 37, 'typology_id' => 17],
    ['restaurant_id' => 38, 'typology_id' => 18],
    ['restaurant_id' => 39, 'typology_id' => 19],
    ['restaurant_id' => 40, 'typology_id' => 20]
];